<?php

return array(
	"waves_assets" => "Waves Assets",
	"add_waves_asset" => "Add Waves Asset",
	"add_asset" => "Add Asset",
	"edit_waves_asset" => "Edit Waves Asset",
	"add" => "Add",
	"edit" => "Edit",
	"save" => "Save",
	"delete" => "Delete",
	"yes" => "Yes",
	"no" => "No",
	"asset_name" => "Asset name",
	"asset_id" => "Asset id",
	"decimal_points" => "Decimal points",
	"delete_waves_asset" => "Delete Waves Asset",
	"are_you_sure_to_delete_asset" => "Are you sure you want to delete the ^ asset?",
	"waves_acct" => "Waves Account",
	"waves_acct_addr" => "Waves Account Address",
	"waves_acct_addr_label" => "The Waves account address to receive payments",
	"waves_acct_addr_label_none" => "No Waves account to receive payments",
	"add_waves_acct" => "Add Waves Account",
	"edit_waves_acct" => "Edit Waves Account",
	"waves_payments" => "Waves Payments",
	"waves_payment_rec" => "Waves Payment Record",
	"date" => "Date",
	"txid" => "TXID",
	"asset" => "Asset",
	"amount" => "Amount",
	"purpose" => "Purpose",
	"prev" => "Prev",
	"next" => "Next",
	"no_payment_rec" => "No payment record",
);
